export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const FILTER_USERS = 'FILTER_USERS';
export const CLEAR_FILTERED_USERS = 'CLEAR_FILTERED_USERS';
export const CLEAR_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const FETCH_FACILITIES_SUCCESS = 'FETCH_FACILITIES_SUCCESS';
export const FETCH_FACILITY_SUCCESS = 'FETCH_FACILITY_SUCCESS';
export const FETCH_TOP_FACILITIES_SUCCESS = 'FETCH_TOP_FACILITIES_SUCCESS';
export const CREATE_FACILITY_SUCCESS = 'CREATE_FACILITY_SUCCESS';
export const DELETE_FACILITY_SUCCESS = 'DELETE_FACILITY_SUCCESS';
export const SEARCH_FACILITIES_SUCCESS = 'SEARCH_FACILITIES_SUCCESS';
export const FILTER_FACILITIES = 'FILTER_FACILITIES';
export const CLEAR_FILTERED_FACILITIES = 'CLEAR_FILTERED_FACILITIES';
export const SET_CURRENT_FACILITY = 'SET_CURRENT_FACILITY';
export const CLEAR_CURRENT_FACILITY = 'CLEAR_CURRENT_FACILITY';

export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const CREATE_ROOM_SUCCESS = 'CREATE_ROOM_SUCCESS';
export const DELETE_ROOM_SUCCESS = 'DELETE_ROOM_SUCCESS';
export const SEARCH_ROOMS_SUCCESS = 'SEARCH_ROOMS_SUCCESS';
export const FILTER_ROOMS = 'FILTER_ROOMS';
export const CLEAR_FILTERED_ROOMS = 'CLEAR_FILTERED_ROOMS';
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM';
export const CLEAR_CURRENT_ROOM = 'CLEAR_CURRENT_ROOM';
