export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';

export const FETCH_FACILITIES_SUCCESS = 'FETCH_FACILITIES_SUCCESS';

export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
