export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const SEARCH_FACILITIES_SUCCESS = 'SEARCH_FACILITIES_SUCCESS';
export const FILTER_FACILITIES = 'FILTER_FACILITIES';
export const CLEAR_FILTERED_FACILITIES = 'CLEAR_FILTERED_FACILITIES';

export const FETCH_FACILITIES_SUCCESS = 'FETCH_FACILITIES_SUCCESS';

export const FETCH_ROOMS_SUCCESS = 'FETCH_ROOMS_SUCCESS';
